name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      env:
        NODE_ENV: development
        JSONPLACEHOLDER_URL: https://jsonplaceholder.typicode.com
        JSONPLACEHOLDER_TIMEOUT: 5000
        TYPEORM_CONNECTION: mysql
        TYPEORM_USERNAME: root
        TYPEORM_PASSWORD: 
        TYPEORM_HOST: localhost
        TYPEORM_PORT: 3306
        TYPEORM_DATABASE: nestjs_seed
        TYPEORM_MIGRATIONS: migration/*.ts
        TYPEORM_MIGRATIONS_DIR: migration
        APM_SERVICE_NAME: 
        APM_SERVICE_URL:
        CI: true    
      run: |
        npm ci
        npm run build --if-present
        npm run test:cov
